 # config variable for LibreOffice
 # this file is intended to be able to be included in a Makefile
 # and not to be sourced in a shell session
 #

# Horrible hack to prepend spaces to expansions
# Spaces are usually eaten by make parser but not if variable expands to space.
# Space prefix is desirable because system CFLAGS may be completely empty,
# which means that the variables defined here would need extra twiddling
# to get them into invoked external configures and override pkg-config there.
gb_SPACE:=$(gb_SPACE) $(gb_SPACE)
export SRC_ROOT=/workspace/libreoffice/arm
export BUILDDIR=/workspace/libreoffice/arm

# export AFLAGS=
export ABW_CFLAGS=$(gb_SPACE)
export ABW_LIBS=$(gb_SPACE)
export ALLOC=
export ANDROID_NDK_HOME=
export ANDROID_APP_ABI=
export ANDROID_SDK_HOME=
export ANDROID_PACKAGE_NAME=
export ANDROID_GCC_TOOLCHAIN_VERSION=
export ANT=
export ANT_HOME=
export ANT_LIB=
export APR_CFLAGS=$(gb_SPACE)
export APR_LIBS=$(gb_SPACE)
export AR=arm-linux-gnueabi-ar
export ASSERT_ALWAYS_ABORT=FALSE
export ATL_INCLUDE=
export ATL_LIB=
export AVAHI_CFLAGS=$(gb_SPACE)
export AVAHI_LIBS=$(gb_SPACE)
export LIBATOMIC_OPS_CFLAGS=$(gb_SPACE)
export LIBATOMIC_OPS_LIBS=$(gb_SPACE)
export BOOST_CPPFLAGS=-I/workspace/libreoffice/arm/external/boost/include -I/workspace/libreoffice/arm/workdir/UnpackedTarball/boost
export BOOST_CXXFLAGS=-D_GLIBCXX_HAS_GTHREADS
export BOOST_LOCALE_LIB=
export BOOST_DATE_TIME_LIB=
export BOOST_FILESYSTEM_LIB=
export BOOST_IOSTREAMS_LIB=
export BOOST_LDFLAGS=
export BOOST_SYSTEM_LIB=
export BRAND_INTRO_IMAGES=flat_logo.svg intro.png intro-highres.png
export BREAKPAD_SYMBOL_CONFIG=
export BSH_JAR=
export BUILD_PLATFORM=x86_64-pc-linux-gnu
export BUILD_POSTGRESQL_SDBC=
export BUILD_TYPE=LibO DESKTOP AVMEDIA DBCONNECTIVITY UCPP CLUCENE EXPAT REVENGE ODFGEN EPUBGEN WPD WPG WPS VISIO CDR MSPUB MWAW ETONYEK FREEHAND EBOOK ABW PAGEMAKER QXP ZMF STAROFFICE LIBCMIS LCMS2 BOOST MDDS GLM OPENLDAP SANE ORCUS GRAPHITE HARFBUZZ NEON REDLAND HUNSPELL HYPHEN MYTHES LIBEXTTEXTCAT EPOXY OPENCL POPPLER LIBGPGERROR LIBASSUAN GPGMEPP MORE_FONTS LIBLANGTAG
export BUILD_UNOWINREG=
export BUILD_VER_STRING=
export BUILD_X64=
export BZIP2_CFLAGS=$(gb_SPACE)
export BZIP2_LIBS=$(gb_SPACE)
export CAIRO_CFLAGS=$(gb_SPACE)-isystem /home/lijin.lj/workspace/libreoffice/arm/alios/out/platforms/tv.m648.mstar.userdebug.arm/target/rootfs/usr/include/ -isystem /home/lijin.lj/workspace/libreoffice/arm/alios/out/platforms/tv.m648.mstar.userdebug.arm/target/rootfs/usr/include/cairo
export CAIRO_LIBS=$(gb_SPACE) -L/home/lijin.lj/workspace/libreoffice/arm/alios/out/platforms/tv.m648.mstar.userdebug.arm/target/rootfs/usr/lib -lcairo
export CC=/usr/bin/ccache arm-linux-gnueabi-gcc
export CDR_CFLAGS=$(gb_SPACE)
export CDR_LIBS=$(gb_SPACE)
 export CFLAGS=-I/home/lijin.lj/workspace/libreoffice/arm/alios/out/platforms/tv.m648.mstar.userdebug.arm/target/rootfs/usr/include/
export CLANGDIR=
export CLANGLIBDIR=
export CLUCENE_CFLAGS=$(gb_SPACE)
export CLUCENE_LIBS=$(gb_SPACE)
export LIBCMIS_CFLAGS=$(gb_SPACE)
export LIBCMIS_LIBS=$(gb_SPACE)
export COM=GCC
export COMMONS_LOGGING_JAR=
export COMMONS_LOGGING_VERSION=1.2
export COMPATH=/home/lijin.lj/workspace/libreoffice/arm/alios/arm/arm-linux-gnueabi-4.9-glibc-2.20/bin/
export COMPILER_PLUGINS=
export COMPILER_PLUGINS_CXX=
export COMPILER_PLUGINS_CXX_LINKFLAGS=
export COM_IS_CLANG=
export CPPUNIT_CFLAGS=$(gb_SPACE)
export CPPUNIT_LIBS=$(gb_SPACE)
export CPUNAME=ARM
export CROSS_COMPILING=TRUE
export CURL=/usr/bin/curl
export CURL_CFLAGS=$(gb_SPACE)-I/home/lijin.lj/workspace/libreoffice/arm/alios/third_party/curl/include -I/home/lijin.lj/workspace/libreoffice/arm/alios/third_party/curl/include/curl
export CURL_LIBS=$(gb_SPACE)-L/home/lijin.lj/workspace/libreoffice/arm/alios/out/platforms/tv.m648.mstar.userdebug.arm/target/rootfs/usr/lib -lcurl -lssl -lcrypto
export CUSTOM_BRAND_DIR=
export CUSTOM_BRAND_IMAGES=
export CXX=/usr/bin/ccache arm-linux-gnueabi-g++
export CXX_X64_BINARY=
# export CXXFLAGS=
export CXXFLAGS_CXX11=-std=gnu++14
export DATADIR=/usr/local/share
export DBUS_CFLAGS=$(gb_SPACE)
export DBUS_LIBS=$(gb_SPACE)
export DCONF_CFLAGS=
export DCONF_LIBS=
export DEFAULT_BRAND_IMAGES=flat_logo.svg intro.png intro-highres.png about.svg
export DICT_SYSTEM_DIR=file:///usr/share/hunspell
export DISABLE_CVE_TESTS=TRUE
export DISABLE_DYNLOADING=TRUE
export DISABLE_OPENSSL=
export DISABLE_PYTHON=TRUE
export DLOPEN_LIBS=-ldl
export DLLTOOL=
export DOCDIR=/usr/local/share/doc/libreoffice
export DOXYGEN=
export DO_FETCH_TARBALLS=TRUE
export DPKG=
export EBOOK_CFLAGS=$(gb_SPACE)
export EBOOK_LIBS=$(gb_SPACE)
export ENABLE_AVAHI=
export ENABLE_BREAKPAD=
export ENABLE_CAIRO_CANVAS=
export ENABLE_CHART_TESTS=
export ENABLE_LIBCMIS=TRUE
export ENABLE_COINMP=
export SYSTEM_COINMP=
export COINMP_CFLAGS=
export COINMP_LIBS=
export ENABLE_CUPS=
export ENABLE_CURL=TRUE
export ENABLE_FUZZERS=
export ENABLE_DBGUTIL=
export ENABLE_DBUS=
export ENABLE_DCONF=
export ENABLE_DEBUG=
export ENABLE_DEBUGINFO_FOR=
export ENABLE_EOT=
export ENABLE_EVOAB2=
export ENABLE_FIREBIRD_SDBC=
export ENABLE_FORMULA_LOGGER=
export ENABLE_GIO=
export ENABLE_GPGMEPP=TRUE
export ENABLE_GSTREAMER_0_10=
export ENABLE_GSTREAMER_1_0=
export ENABLE_GTK3=
export ENABLE_GTK=
export ENABLE_GTK_PRINT=
export ENABLE_HEADLESS=TRUE
export ENABLE_JAVA=
export ENABLE_KDE4=
export ENABLE_LPSOLVE=
export ENABLE_LTO=
export ENABLE_LWP=
export ENABLE_MACOSX_SANDBOX=
export ENABLE_MEDIAWIKI=
export ENABLE_MARIADBC=
export ENABLE_NSS=TRUE
export ENABLE_ONLINE_UPDATE=
export ENABLE_ONLINE_UPDATE_MAR=
export ENABLE_EXTENSION_UPDATE=TRUE
export ENABLE_OOENV=
export ENABLE_OPENGL_TRANSITIONS=
export ENABLE_OPENGL_CANVAS=
export ENABLE_OPTIMIZED=TRUE
export ENABLE_PCH=
export ENABLE_PDFIMPORT=TRUE
export ENABLE_PDFIUM=
export ENABLE_QT5=
export ENABLE_RANDR=
export ENABLE_RELEASE_BUILD=
export ENABLE_REPORTBUILDER=
export ENABLE_RUNTIME_OPTIMIZATIONS=TRUE
export ENABLE_SAL_LOG=TRUE
export ENABLE_SCRIPTING_BEANSHELL=
export ENABLE_SCRIPTING_JAVASCRIPT=
export ENABLE_SDREMOTE=
export ENABLE_SDREMOTE_BLUETOOTH=
export ENABLE_SILENT_MSI=
export ENABLE_SYMBOLS=
export ENABLE_SYSTRAY_GTK=
export ENABLE_VALGRIND=
export ENABLE_VLC=
export ENABLE_WERROR=
export EPM=NO
export EPM_FLAGS=-a arm
export EPUBGEN_CFLAGS=$(gb_SPACE)
export EPUBGEN_LIBS=$(gb_SPACE)
export ETONYEK_CFLAGS=$(gb_SPACE)
export ETONYEK_LIBS=$(gb_SPACE)
export debug=
export FIND=find
export FIREBIRD_CFLAGS=$(gb_SPACE)
export FIREBIRD_LIBS=$(gb_SPACE)
export FLEX=/usr/bin/flex
export FLUTE_JAR=
export FONTCONFIG_CFLAGS=$(gb_SPACE)-I/home/lijin.lj/workspace/libreoffice/arm/alios/out/platforms/tv.m648.mstar.userdebug.arm/target/rootfs/usr/include/
export FONTCONFIG_LIBS=$(gb_SPACE) -L/home/lijin.lj/workspace/libreoffice/arm/alios/out/platforms/tv.m648.mstar.userdebug.arm/target/rootfs/usr/lib -lfontconfig
export FREEHAND_CFLAGS=$(gb_SPACE)
export FREEHAND_LIBS=$(gb_SPACE)
export FREETYPE_CFLAGS=$(gb_SPACE)-isystem /home/lijin.lj/workspace/libreoffice/arm/alios/out/platforms/tv.m648.mstar.userdebug.arm/target/rootfs/usr/include/
export FREETYPE_LIBS=$(gb_SPACE) -L/home/lijin.lj/workspace/libreoffice/arm/alios/out/platforms/tv.m648.mstar.userdebug.arm/target/rootfs/usr/lib -lfreetype
export GCC_VERSION=409
export GIO_CFLAGS=$(gb_SPACE)
export GIO_LIBS=$(gb_SPACE)
export GIT_REFERENCE_SRC=
export GIT_LINK_SRC=
export GIT_NEEDED_SUBMODULES=
export EPOXY_CFLAGS=$(gb_SPACE)-I/workspace/libreoffice/arm/workdir/UnpackedTarball/epoxy/include
export EPOXY_LIBS=$(gb_SPACE)
export GLM_CFLAGS=$(gb_SPACE)-isystem /workspace/libreoffice/arm/workdir/UnpackedTarball/glm
export GPG_ERROR_CFLAGS=$(gb_SPACE)-I/workspace/libreoffice/arm/workdir/UnpackedTarball/libgpg-error/src
export GPG_ERROR_LIBS=$(gb_SPACE)-L/workspace/libreoffice/arm/workdir/UnpackedTarball/libgpg-error/src/.libs -lgpg-error
export GPGCONF=
export GPGMEPP_CFLAGS=$(gb_SPACE)
export GPGMEPP_LIBS=$(gb_SPACE)
export GNUTLS_CFLAGS=$(gb_SPACE)
export GNUTLS_LIBS=$(gb_SPACE)
export PARALLELISM?=64
 export GNUCOPY=/bin/cp
export GNUMAKE_WIN_NATIVE=
export GNUPATCH=/usr/bin/patch
export GNUTAR=tar
export GOBJECT_CFLAGS=$(gb_SPACE)
export GOBJECT_LIBS=$(gb_SPACE)
export GPERF=/usr/bin/gperf
export GRAPHITE_CFLAGS=$(gb_SPACE)-I/workspace/libreoffice/arm/workdir/UnpackedTarball/graphite/include -DGRAPHITE2_STATIC
export GRAPHITE_LIBS=$(gb_SPACE)-L/workspace/libreoffice/arm/workdir/LinkTarget/StaticLibrary -lgraphite
export HARFBUZZ_CFLAGS=$(gb_SPACE)-I/workspace/libreoffice/arm/workdir/UnpackedTarball/harfbuzz/src
export HARFBUZZ_LIBS=$(gb_SPACE)-L/workspace/libreoffice/arm/workdir/UnpackedTarball/harfbuzz/src/.libs -lharfbuzz
# export GREP=
export GSSAPI_LIBS=
export GSTREAMER_0_10_CFLAGS=$(gb_SPACE)
export GSTREAMER_0_10_LIBS=$(gb_SPACE)
export GSTREAMER_1_0_CFLAGS=$(gb_SPACE)
export GSTREAMER_1_0_LIBS=$(gb_SPACE)
export GTHREAD_CFLAGS=$(gb_SPACE)
export GTHREAD_LIBS=$(gb_SPACE)
export GTK3_CFLAGS=$(gb_SPACE)
export GTK3_LIBS=$(gb_SPACE)
export GTK_CFLAGS=$(gb_SPACE)
export GTK_LIBS=$(gb_SPACE)
export GTK_PRINT_CFLAGS=$(gb_SPACE)
export GTK_PRINT_LIBS=$(gb_SPACE)
export USING_X11=
export HAMCREST_JAR=
export HAVE_GCC_AVX=
export HAVE_GCC_STACK_PROTECTOR_STRONG=TRUE
export HAVE_GCC_BUILTIN_ATOMIC=TRUE
export HAVE_GCC_BUILTIN_FFS=TRUE
export HAVE_GCC_FINLINE_LIMIT=TRUE
export HAVE_GCC_FNO_DEFAULT_INLINE=TRUE
export HAVE_GCC_FNO_ENFORCE_EH_SPECS=TRUE
export HAVE_GCC_FNO_INLINE=TRUE
export HAVE_GCC_FNO_SIZED_DEALLOCATION=
export HAVE_GCC_GGDB2=TRUE
export HAVE_GNUMAKE_FILE_FUNC=
export HAVE_GPGCONF_SOCKETDIR=
export HAVE_LD_BSYMBOLIC_FUNCTIONS=TRUE
export HAVE_LD_HASH_STYLE=FALSE
export HAVE_POSIX_FALLOCATE=YES
export HELP_COMMON_ONLY=FALSE
export HOST_PLATFORM=arm-unknown-linux-gnueabi
export HSQLDB_JAR=
export HSQLDB_USE_JDBC_4_1=
export HUNSPELL_CFLAGS=$(gb_SPACE)-I/workspace/libreoffice/arm/workdir/UnpackedTarball/hunspell/src/hunspell
export HUNSPELL_LIBS=$(gb_SPACE)-L/workspace/libreoffice/arm/workdir/UnpackedTarball/hunspell/src/hunspell/.libs -lhunspell-1.6
export HYPHEN_LIB=$(gb_SPACE)-L/workspace/libreoffice/arm/workdir/UnpackedTarball/hyphen/.libs -lhyphen
export HYPH_SYSTEM_DIR=file:///usr/share/hyphen
export ICECREAM_RUN=
# export ICECC_VERSION=
export ICU_CFLAGS=$(gb_SPACE)-I/home/lijin.lj/workspace/libreoffice/arm/alios/out/platforms/tv.m648.mstar.userdebug.arm/target/rootfs/usr/include/
export ICU_LIBS=$(gb_SPACE)-L/home/lijin.lj/workspace/libreoffice/arm/alios/out/platforms/tv.m648.mstar.userdebug.arm/target/rootfs/usr/lib -licui18n -licudata -licuuc
export ICU_MAJOR=60
export ICU_MINOR=
export ICU_RECLASSIFIED_CONDITIONAL_JAPANESE_STARTER=TRUE
export ICU_RECLASSIFIED_HEBREW_LETTER=TRUE
export ICU_RECLASSIFIED_PREPEND_SET_EMPTY=TRUE
export ICU_UCHAR_TYPE=-DUCHAR_TYPE=uint16_t
export INTROSPECTION_SCANNER=
export ILIB=
export INSTALLDIR=/usr/local/lib/libreoffice
export INSTALLDIRNAME=libreoffice
export INSTALL_NAME_TOOL=
export INSTDIR=/workspace/libreoffice/arm/instdir
export INSTDIR_FOR_BUILD=/workspace/libreoffice/arm/instdir_for_build
export INSTROOT=/workspace/libreoffice/arm/instdir
export INSTROOTBASE=/workspace/libreoffice/arm/instdir
export INSTROOT_FOR_BUILD=/workspace/libreoffice/arm/instdir_for_build
export IWYU_PATH=
export JAVACOMPILER=
export JAVADOC=
export JAVADOCISGJDOC=
export JAVAFLAGS=
export JAVAIFLAGS=
export JAVA_CLASSPATH_NOT_SET=
export JAVAINTERPRETER=
export JAVA_HOME=
export JAVA_SOURCE_VER=
export JAVA_TARGET_VER=
export JAWTLIB=
export JDK=
export JFREEREPORT_JAR=
export JITC_PROCESSOR_TYPE=
export JVM_ONE_PATH_CHECK=
export KDE4_CFLAGS=$(gb_SPACE)
export KDE4_LIBS=$(gb_SPACE)
export KDE4_GLIB_CFLAGS=$(gb_SPACE)
export KDE4_GLIB_LIBS=$(gb_SPACE)
export KDE4_HAVE_GLIB=
export KF5_CFLAGS=$(gb_SPACE)
export KF5_LIBS=$(gb_SPACE)
export KRB5_LIBS=
export LCMS2_CFLAGS=$(gb_SPACE)-I/workspace/libreoffice/arm/workdir/UnpackedTarball/lcms2/include -Wno-long-long
export LCMS2_LIBS=$(gb_SPACE)-L/workspace/libreoffice/arm/workdir/UnpackedTarball/lcms2/src/.libs -llcms2
export LD_PLUGIN=
 export LDFLAGS=-L/home/lijin.lj/workspace/libreoffice/arm/alios/out/platforms/tv.m648.mstar.userdebug.arm/target/rootfs/usr/lib
export LFS_CFLAGS=-D_FILE_OFFSET_BITS=64
export LIBASSUAN_CFLAGS=$(gb_SPACE)-I/workspace/libreoffice/arm/workdir/UnpackedTarball/libassuan/src
export LIBASSUAN_LIBS=$(gb_SPACE)-L/workspace/libreoffice/arm/workdir/UnpackedTarball/libassuan/src/.libs -lassuan
export LIBBASE_JAR=
export LIBDIR=/usr/local/lib
export LIBEOT_CFLAGS=$(gb_SPACE)
export LIBEOT_LIBS=$(gb_SPACE)
export LIBEXSLT_CFLAGS=$(gb_SPACE)-isystem /usr/include/libxml2
export LIBEXSLT_LIBS=$(gb_SPACE) -lexslt -lxslt -lxml2
export LIBEXTTEXTCAT_CFLAGS=$(gb_SPACE)
export LIBEXTTEXTCAT_LIBS=$(gb_SPACE)
export LIBFONTS_JAR=
export LIBFORMULA_JAR=
export LIBGCRYPT_CFLAGS=
export LIBGCRYPT_LIBS=
export LIBJPEG_CFLAGS=$(gb_SPACE)-I/home/lijin.lj/workspace/libreoffice/arm/alios/out/platforms/tv.m648.mstar.userdebug.arm/target/rootfs/usr/include/
export LIBJPEG_LIBS=$(gb_SPACE)-L/home/lijin.lj/workspace/libreoffice/arm/alios/out/platforms/tv.m648.mstar.userdebug.arm/target/rootfs/usr/lib -ljpeg
export LIBLANGTAG_CFLAGS=$(gb_SPACE)-I/workspace/libreoffice/arm/workdir/UnpackedTarball/liblangtag
export LIBLANGTAG_LIBS=$(gb_SPACE)-L/workspace/libreoffice/arm/workdir/UnpackedTarball/liblangtag/liblangtag/.libs -llangtag
export LIBLAYOUT_JAR=
export LIBLOADER_JAR=
export LIBO_BIN_FOLDER=program
export LIBO_BIN_FOLDER_FOR_BUILD=program
export LIBO_ETC_FOLDER=program
export LIBO_LIB_FOLDER=program
export LIBO_LIB_FOLDER_FOR_BUILD=program
export LIBO_LIB_PYUNO_FOLDER=program
export LIBO_SHARE_FOLDER=share
export LIBO_SHARE_HELP_FOLDER=help
export LIBO_SHARE_JAVA_FOLDER=program/classes
export LIBO_SHARE_PRESETS_FOLDER=presets
export LIBO_SHARE_READMES_FOLDER=readmes
export LIBO_SHARE_RESOURCE_FOLDER=program/resource
export LIBO_URE_BIN_FOLDER=program
export LIBO_URE_ETC_FOLDER=program
export LIBO_URE_LIB_FOLDER=program
export LIBO_URE_LIB_FOLDER_FOR_BUILD=program
export LIBO_URE_MISC_FOLDER=program
export LIBO_URE_MISC_FOLDER_FOR_BUILD=program
export LIBO_URE_SHARE_JAVA_FOLDER=program/classes
export LIBO_VERSION_MAJOR=6
export LIBO_VERSION_MICRO=5
export LIBO_VERSION_MINOR=0
export LIBO_VERSION_PATCH=2
export LIBO_VERSION_SUFFIX=
export LIBO_VERSION_SUFFIX_SUFFIX=
export LIBPNG_CFLAGS=$(gb_SPACE)-isystem /home/lijin.lj/workspace/libreoffice/arm/alios/out/platforms/tv.m648.mstar.userdebug.arm/target/rootfs/usr/include/
export LIBPNG_LIBS=$(gb_SPACE) -L/home/lijin.lj/workspace/libreoffice/arm/alios/out/platforms/tv.m648.mstar.userdebug.arm/target/rootfs/usr/lib -lpng
export LIBREPOSITORY_JAR=
export LIBSERIALIZER_JAR=
export LIBTOOL=
export LIBXML_CFLAGS=$(gb_SPACE)-isystem /home/lijin.lj/workspace/libreoffice/arm/alios/out/platforms/tv.m648.mstar.userdebug.arm/target/rootfs/usr/include/ -isystem /home/lijin.lj/workspace/libreoffice/arm/alios/out/platforms/tv.m648.mstar.userdebug.arm/target/rootfs/usr/include/libxml2
export LIBXML_JAR=
export LIBXML_LIBS=$(gb_SPACE) -L/home/lijin.lj/workspace/libreoffice/arm/alios/out/platforms/tv.m648.mstar.userdebug.arm/target/rootfs/usr/lib -lxml2 -lz -llzma
export LIBXSLT_CFLAGS=$(gb_SPACE)-isystem /home/lijin.lj/workspace/libreoffice/arm/alios/out/platforms/tv.m648.mstar.userdebug.arm/target/rootfs/usr/include/ -isystem /home/lijin.lj/workspace/libreoffice/arm/alios/out/platforms/tv.m648.mstar.userdebug.arm/target/rootfs/usr/include/libxml2
export LIBXSLT_LIBS=$(gb_SPACE) -L/home/lijin.lj/workspace/libreoffice/arm/alios/out/platforms/tv.m648.mstar.userdebug.arm/target/rootfs/usr/lib -lxslt
export LINK_X64_BINARY=
# export LS=
export MACOSX_BUNDLE_IDENTIFIER=
export MACOSX_CODESIGNING_IDENTITY=
export MACOSX_DEPLOYMENT_TARGET=
export MACOSX_PACKAGE_SIGNING_IDENTITY=
export MACOSX_SDK_PATH=
export MACOSX_SDK_VERSION=
export MAC_OS_X_VERSION_MAX_ALLOWED=
export MAC_OS_X_VERSION_MIN_REQUIRED=
export MAC_OS_X_VERSION_MIN_REQUIRED_DOTS=
export MANDIR=/usr/local/share/man
export MARIADBC_MAJOR=
export MARIADBC_MICRO=
export MARIADBC_MINOR=
export MARIADB_CFLAGS=$(gb_SPACE)
export MARIADB_LIBS=$(gb_SPACE)
export LIBMARIADB=
export LIBMARIADB_PATH=
export BUNDLE_MARIADB_CONNECTOR_C=
export MDDS_CFLAGS=$(gb_SPACE)-I/workspace/libreoffice/arm/workdir/UnpackedTarball/mdds/include
export MDDS_LIBS=$(gb_SPACE)
export MERGELIBS=
export MINGWCXX=
export MINGWSTRIP=
export ML_EXE=
export MOC4=moc
export MOC5=moc
export MPL_SUBSET=
export MSGFMT=
export MSGUNIQ=
export MSM_PATH=
export MSPUB_CFLAGS=$(gb_SPACE)
export MSPUB_LIBS=$(gb_SPACE)
export MSVC_CXX=
export MSVC_DLLS=
export MSVC_DLL_PATH=
export MSVC_USE_DEBUG_RUNTIME=
export MWAW_CFLAGS=$(gb_SPACE)
export MWAW_LIBS=$(gb_SPACE)
export MYTHES_CFLAGS=$(gb_SPACE)
export MYTHES_LIBS=$(gb_SPACE)-L/workspace/libreoffice/arm/workdir/UnpackedTarball/mythes/.libs -lmythes-1.2
export NASM=
export NEON_CFLAGS=$(gb_SPACE)
export NEON_LIBS=$(gb_SPACE)
export NEON_VERSION=0295
export NM=arm-linux-gnueabi-nm
export NSS_CFLAGS=$(gb_SPACE)-isystem /home/lijin.lj/workspace/libreoffice/arm/alios/out/platforms/tv.m648.mstar.userdebug.arm/target/rootfs/usr/include/ -isystem /home/lijin.lj/workspace/libreoffice/arm/alios/out/platforms/tv.m648.mstar.userdebug.arm/target/rootfs/usr/include/nss3 -isystem /home/lijin.lj/workspace/libreoffice/arm/alios/out/platforms/tv.m648.mstar.userdebug.arm/target/rootfs/usr/include/nspr4
export NSS_LIBS=$(gb_SPACE) -L/home/lijin.lj/workspace/libreoffice/arm/alios/out/platforms/tv.m648.mstar.userdebug.arm/target/rootfs/usr/lib -lnspr4 -lnss3 -lsmime3 -lplc4 -lnssutil3 -lplds4
export NUMBERTEXT_EXTENSION_PACK=
export nodep=
# export OBJCFLAGS=
# export OBJCXXFLAGS=
export OBJDUMP=arm-linux-gnueabi-objdump
export ODFGEN_CFLAGS=$(gb_SPACE)
export ODFGEN_LIBS=$(gb_SPACE)
export ODFVALIDATOR=
export OFFICEOTRON=
export BFFVALIDATOR=
export OOO_JUNIT_JAR=
export OOO_VENDOR=root
export OPENSSL_CFLAGS=$(gb_SPACE)-isystem /home/lijin.lj/workspace/libreoffice/arm/alios/out/platforms/tv.m648.mstar.userdebug.arm/target/rootfs/usr/include/
export OPENSSL_LIBS=$(gb_SPACE) -L/home/lijin.lj/workspace/libreoffice/arm/alios/out/platforms/tv.m648.mstar.userdebug.arm/target/rootfs/usr/lib -lssl -lcrypto
export ORCUS_CFLAGS=$(gb_SPACE)
export ORCUS_LIBS=$(gb_SPACE)
export OS=LINUX
export OS_FOR_BUILD=LINUX
export PATH=/home/lijin.lj/workspace/libreoffice/arm/alios/opt/bin:/home/lijin.lj/workspace/libreoffice/arm/alios/arm/arm-linux-gnueabi-4.9-glibc-2.20/bin/:/home/lijin.lj/workspace/libreoffice/arm/alios/opt/bin:/home/lijin.lj/workspace/libreoffice/arm/alios/arm/arm-linux-gnueabi-4.9-glibc-2.20/bin/:/home/lijin.lj/bin:/home/lijin.lj/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/lijin.lj/bin:/home/lijin.lj/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games
export LIBO_PATH_SEPARATOR=:
export PAGEMAKER_CFLAGS=$(gb_SPACE)
export PAGEMAKER_LIBS=$(gb_SPACE)
export PERL=/usr/bin/perl
export PKGFORMAT=
export PKGMK=
export PKG_CONFIG=/usr/bin/pkg-config
export PLATFORMID=linux_arm_eabi
export POPPLER_CFLAGS=$(gb_SPACE)
export POPPLER_LIBS=$(gb_SPACE)
export POSTGRESQL_INC=
export POSTGRESQL_LIB=
export PREFIXDIR=/usr/local
export PRODUCTNAME=LibreOfficeDev
export PRODUCTNAME_WITHOUT_SPACES=LibreOfficeDev
export PRODUCTVERSION=6.0
export PROGRESSBARCOLOR=
export PROGRESSFRAMECOLOR=
export PROGRESSPOSITION=
export PROGRESSSIZE=
export PROGRESSTEXTBASELINE=
export PROGRESSTEXTCOLOR=
export PTHREAD_CFLAGS=
export PTHREAD_LIBS=
export PYTHON_CFLAGS=$(gb_SPACE)
export PYTHON_FOR_BUILD=/usr/bin/python
export PYTHON_LIBS=$(gb_SPACE)
export PYTHON_VERSION=
export PYTHON_VERSION_MAJOR=
export PYTHON_VERSION_MINOR=
export QT5_CFLAGS=$(gb_SPACE)
export QT5_LIBS=$(gb_SPACE)
export QT5_GLIB_CFLAGS=$(gb_SPACE)
export QT5_GLIB_LIBS=$(gb_SPACE)
export QT5_HAVE_GLIB=
export QXP_CFLAGS=$(gb_SPACE)
export QXP_LIBS=$(gb_SPACE)
export RANLIB=arm-linux-gnueabi-ranlib
export RAPTOR_MAJOR=0
export RASQAL_MAJOR=3
export READELF=arm-linux-gnueabi-readelf
export REDLAND_CFLAGS=$(gb_SPACE)
export REDLAND_LIBS=$(gb_SPACE)
export REDLAND_MAJOR=0
export REVENGE_CFLAGS=$(gb_SPACE)-I/workspace/libreoffice/arm/workdir/UnpackedTarball/librevenge/inc
export REVENGE_LIBS=$(gb_SPACE)-L/workspace/libreoffice/arm/workdir/UnpackedTarball/librevenge/src/lib/.libs -lrevenge-0.0
export RHINO_JAR=
export RPM=
export RTL_ARCH=ARM_EABI
export RTL_OS=Linux
export SAC_JAR=
export SAL_ENABLE_FILE_LOCKING=1
export SCPDEFS= -DDISABLE_SCRIPTING -DWITHOUT_EXTENSION_MEDIAWIKI -DWITHOUT_SCRIPTING_BEANSHELL -DWITHOUT_SCRIPTING_JAVASCRIPT -DWITH_EXTENSION_INTEGRATION -DENABLE_EXTENSION_UPDATE
export SDKDIRNAME=sdk
export SDKDIRNAME_FOR_BUILD=sdk
export SERF_CFLAGS=$(gb_SPACE)
export SERF_LIBS=$(gb_SPACE)
export SHA256SUM=shasum -a 256
export SHOWINCLUDES_PREFIX=
export SOLARINC=-I/workspace/libreoffice/arm/include  
export SORT=sort
export SPLIT_APP_MODULES=
export SPLIT_OPT_FEATURES=
export SRCDIR=/workspace/libreoffice/arm
export STAROFFICE_CFLAGS=$(gb_SPACE)
export STAROFFICE_LIBS=$(gb_SPACE)
export STRIP=arm-linux-gnueabi-strip
export STRIP_COMPONENTS=--strip-components
export SYSBASE=
export SYSTEM_ABW=
export SYSTEM_APACHE_COMMONS=
export SYSTEM_APR=
export SYSTEM_BLUEZ=
export SYSTEM_BOOST=
export SYSTEM_BSH=
export SYSTEM_BZIP2=
export SYSTEM_CAIRO=TRUE
export SYSTEM_CLUCENE=
export SYSTEM_CPPUNIT=
export SYSTEM_CURL=TRUE
export SYSTEM_DICTS=TRUE
export SYSTEM_EXPAT=
export SYSTEM_FONTCONFIG=TRUE
export SYSTEM_FREETYPE=TRUE
export SYSTEM_FIREBIRD=
export SYSTEM_GENBRK=/home/lijin.lj/workspace/libreoffice/arm/alios/opt/bin/genbrk
export SYSTEM_GENCCODE=/home/lijin.lj/workspace/libreoffice/arm/alios/opt/bin/genccode
export SYSTEM_GENCMN=/home/lijin.lj/workspace/libreoffice/arm/alios/opt/bin/gencmn
export SYSTEM_EPOXY=
export SYSTEM_GLM=
export SYSTEM_GPGMEPP=
export SYSTEM_GRAPHITE=
export SYSTEM_HARFBUZZ=
export SYSTEM_HSQLDB=
export SYSTEM_HUNSPELL=
export SYSTEM_HYPH=
export SYSTEM_ICU=TRUE
export SYSTEM_JFREEREPORT=
export SYSTEM_LIBJPEG=TRUE
export SYSTEM_LCMS2=
export SYSTEM_CDR=
export SYSTEM_LIBCMIS=
export SYSTEM_EBOOK=
export SYSTEM_ETONYEK=
export SYSTEM_EPUBGEN=
export SYSTEM_FREEHAND=
export SYSTEM_LIBATOMIC_OPS=
export SYSTEM_LIBEOT=
export SYSTEM_LIBEXTTEXTCAT=
export SYSTEM_LIBEXTTEXTCAT_DATA=
export SYSTEM_LIBLANGTAG=
export SYSTEM_LIBORCUS=
export SYSTEM_LIBPNG=TRUE
export SYSTEM_LIBXML=TRUE
export SYSTEM_LIBXML_FOR_BUILD=TRUE
export SYSTEM_LIBXSLT=TRUE
export SYSTEM_LIBXSLT_FOR_BUILD=TRUE
export SYSTEM_LPSOLVE=
export SYSTEM_MDDS=
export SYSTEM_MARIADB_CONNECTOR_C=
export SYSTEM_MSPUB=
export SYSTEM_MWAW=
export SYSTEM_MYSQL_CONNECTOR_CPP=
export SYSTEM_MYTHES=
export SYSTEM_NEON=
export SYSTEM_NSS=TRUE
export SYSTEM_ODBC_HEADERS=
export SYSTEM_ODFGEN=
export SYSTEM_OPENLDAP=
export SYSTEM_OPENSSL=TRUE
export SYSTEM_PAGEMAKER=
export SYSTEM_POPPLER=
export SYSTEM_POSTGRESQL=
export SYSTEM_PYTHON=
export SYSTEM_QXP=
export SYSTEM_REDLAND=
export SYSTEM_REVENGE=
export SYSTEM_RHINO=
export SYSTEM_SERF=
export SYSTEM_STAROFFICE=
export SYSTEM_UCPP=
export SYSTEM_VISIO=
export SYSTEM_WPD=
export SYSTEM_WPG=
export SYSTEM_WPS=
export SYSTEM_XMLSEC=TRUE
export SYSTEM_ZLIB=TRUE
export SYSTEM_ZMF=
export TARFILE_LOCATION=/workspace/libreoffice/arm/external/tarballs
export TESTINSTALLDIR=/workspace/libreoffice/arm/test-install
export THES_SYSTEM_DIR=file:///usr/share/mythes
export TLS=NSS
export TMPDIR=/tmp
export TOUCH=/usr/bin/touch
export UCRTSDKDIR=
export UCRTVERSION=
export VCREDIST_DIR=
export VCREDIST_EXE=
export UNOWINREG_DLL=185d60944ea767075d27247c3162b3bc-unowinreg.dll
export USE_LIBRARY_BIN_TAR=
export USE_XINERAMA=
export UPDATE_CONFIG=
export UUIDGEN=
export VALGRIND_CFLAGS=$(gb_SPACE)
export VCVER=
export DEVENV=
export VISIO_CFLAGS=$(gb_SPACE)
export VISIO_LIBS=$(gb_SPACE)
export WGET=wget
export WINDOWS_BUILD_SIGNING=FALSE
export WINDOWS_SDK_HOME=
export WINDOWS_SDK_LIB_SUBDIR=
export WINDOWS_SDK_VERSION=
export WINDOWS_SDK_WILANGID=
export WINDOWS_X64=
export WINDRES=
export WITH_COMPAT_OOWRAPPERS=
export WITH_EXTENSION_INTEGRATION=TRUE
export WITH_EXTRA_EXTENSIONS=
export WITH_FONTS=TRUE
export WITH_GALLERY_BUILD=
export WITH_GSSAPI=
export WITH_HELPPACK_INTEGRATION=
export WITH_KRB5=
export WITH_LINKER_HASH_STYLE=
export WITH_LOCALES=
export WITH_MYSPELL_DICTS=
export WITH_POOR_HELP_LOCALIZATIONS=
export WITH_THEMES= breeze breeze_dark elementary galaxy hicontrast sifr sifr_dark tango 
export WITH_WEBDAV=neon
export WORKDIR=/workspace/libreoffice/arm/workdir
export WORKDIR_FOR_BUILD=/workspace/libreoffice/arm/workdir_for_build
export WPD_CFLAGS=$(gb_SPACE)-I/workspace/libreoffice/arm/workdir/UnpackedTarball/libwpd/inc
export WPD_LIBS=$(gb_SPACE)-L/workspace/libreoffice/arm/workdir/UnpackedTarball/libwpd/src/lib/.libs -lwpd-0.10
export WPG_CFLAGS=$(gb_SPACE)
export WPG_LIBS=$(gb_SPACE)
export WPS_CFLAGS=$(gb_SPACE)
export WPS_LIBS=$(gb_SPACE)
export IOS_SDK=
export IOS_DEPLOYMENT_VERSION=
export XINERAMA_LINK=none
export XMLLINT=/usr/bin/xmllint
export XMLSEC_CFLAGS=$(gb_SPACE)-isystem /home/lijin.lj/workspace/libreoffice/arm/alios/third_party/xmlsec1/include/
export XMLSEC_LIBS=$(gb_SPACE) -L/home/lijin.lj/workspace/libreoffice/arm/alios/out/platforms/tv.m648.mstar.userdebug.arm/target/rootfs/usr/lib -lxmlsec1 -lxmlsec1-nss -lltdl
export XRANDR_CFLAGS=$(gb_SPACE)
export XRANDR_LIBS=$(gb_SPACE)
export XRENDER_CFLAGS=$(gb_SPACE)
export XRENDER_LIBS=$(gb_SPACE)
export XSLTPROC=/usr/bin/xsltproc
export ZLIB_CFLAGS=$(gb_SPACE)-I/home/lijin.lj/workspace/libreoffice/arm/alios/out/platforms/tv.m648.mstar.userdebug.arm/target/rootfs/usr/include/
export ZLIB_LIBS=$(gb_SPACE)-L/home/lijin.lj/workspace/libreoffice/arm/alios/out/platforms/tv.m648.mstar.userdebug.arm/target/rootfs/usr/lib -lz -llzma
export ZMF_CFLAGS=$(gb_SPACE)
export ZMF_LIBS=$(gb_SPACE)
export USE_AVMEDIA_DUMMY=

# lang-related stuff
include $(BUILDDIR)/config_$(gb_Side)_lang.mk

# tarball names
# does use some of the variables defined above
include /workspace/libreoffice/arm/download.lst
export PIXMAN_CFLAGS=-I/home/lijin.lj/workspace/libreoffice/arm/alios/out/platforms/tv.m648.mstar.userdebug.arm/target/rootfs/usr/include/pixman-1
export PIXMAN_LIBS=-L/home/lijin.lj/workspace/libreoffice/arm/alios/out/platforms/tv.m648.mstar.userdebug.arm/target/rootfs/usr/lib -lpixman-1
export ALIOS_CFLAGS=-I/home/lijin.lj/workspace/libreoffice/arm/alios/out/platforms/tv.m648.mstar.userdebug.arm/target/rootfs/usr/include/
export ALIOS_LDFLAGS=-L/home/lijin.lj/workspace/libreoffice/arm/alios/out/platforms/tv.m648.mstar.userdebug.arm/target/rootfs/usr/lib
export ALIOS_LOG_CFLAGS=-I/home/lijin.lj/workspace/libreoffice/arm/alios/out/platforms/tv.m648.mstar.userdebug.arm/target/rootfs/usr/include//base
export ALIOS_LOG_LDFLAGS=-L/home/lijin.lj/workspace/libreoffice/arm/alios/out/platforms/tv.m648.mstar.userdebug.arm/target/rootfs/usr/lib -llog
export PIXMAN_CFLAGS=-I/home/lijin.lj/workspace/libreoffice/arm/alios/out/platforms/tv.m648.mstar.userdebug.arm/target/rootfs/usr/include/pixman-1
export PIXMAN_LIBS=-L/home/lijin.lj/workspace/libreoffice/arm/alios/out/platforms/tv.m648.mstar.userdebug.arm/target/rootfs/usr/lib -lpixman-1
export ALIOS_CFLAGS=-I/home/lijin.lj/workspace/libreoffice/arm/alios/out/platforms/tv.m648.mstar.userdebug.arm/target/rootfs/usr/include/
export ALIOS_LDFLAGS=-L/home/lijin.lj/workspace/libreoffice/arm/alios/out/platforms/tv.m648.mstar.userdebug.arm/target/rootfs/usr/lib
export ALIOS_LOG_CFLAGS=-I/home/lijin.lj/workspace/libreoffice/arm/alios/out/platforms/tv.m648.mstar.userdebug.arm/target/rootfs/usr/include//base
export ALIOS_LOG_LDFLAGS=-L/home/lijin.lj/workspace/libreoffice/arm/alios/out/platforms/tv.m648.mstar.userdebug.arm/target/rootfs/usr/lib -llog
export PIXMAN_CFLAGS=-I/home/lijin.lj/workspace/libreoffice/arm/alios/out/platforms/tv.m648.mstar.userdebug.arm/target/rootfs/usr/include/pixman-1
export PIXMAN_LIBS=-L/home/lijin.lj/workspace/libreoffice/arm/alios/out/platforms/tv.m648.mstar.userdebug.arm/target/rootfs/usr/lib -lpixman-1
export ALIOS_CFLAGS=-I/home/lijin.lj/workspace/libreoffice/arm/alios/out/platforms/tv.m648.mstar.userdebug.arm/target/rootfs/usr/include/
export ALIOS_LDFLAGS=-L/home/lijin.lj/workspace/libreoffice/arm/alios/out/platforms/tv.m648.mstar.userdebug.arm/target/rootfs/usr/lib
export ALIOS_LOG_CFLAGS=-I/home/lijin.lj/workspace/libreoffice/arm/alios/out/platforms/tv.m648.mstar.userdebug.arm/target/rootfs/usr/include//base
export ALIOS_LOG_LDFLAGS=-L/home/lijin.lj/workspace/libreoffice/arm/alios/out/platforms/tv.m648.mstar.userdebug.arm/target/rootfs/usr/lib -llog
export LIBEXPAT_LIBS=-L/home/lijin.lj/workspace/libreoffice/arm/alios/out/platforms/tv.m648.mstar.userdebug.arm/target/rootfs/usr/lib -lexpat
